.MODEL SMALL
.STACK 100H
.DATA
	MSG1 DB 0DH,0AH,"ENTER A STRING: $"
	MSG2 DB 0DH,0AH,"ENTER A CHARACTER: $"
	MSG3 DB 0DH,0AH,"CHARACTER FOUND AT POSITION: $"
	MSG4 DB 0DH,0AH,"CHARACTER NOT FOUND!! $"
	STR1 DB 255 DUP(?)
	COUNT DB 2 DUP(?)
.CODE
	START:
		MOV AX,@DATA
		MOV DS,AX
		LEA DX,MSG1
		MOV AH,09H
		INT 21H
		MOV AH,01H
		LEA SI,STR1
	READ:
		INT 21H
		CMP AL,0DH
		JE CHARCHECK
		MOV [SI],AL
		INC SI
		JMP READ
	CHARCHECK:
		MOV AL,'$'
		MOV [SI],AL
		MOV AH,09H
		LEA DX,MSG2
		INT 21H
		MOV AH,01H
		INT 21H
		MOV CL,00H
		LEA SI,STR1
	CHECK:
		CMP AL,[SI]
		JE SUCCESS
		CMP [SI],'$'
		JE FAILURE
		INC SI
		INC CL
		JMP CHECK
	SUCCESS:
		INC CL
		MOV AL,CL
		ADD AL,'0'
		LEA SI,COUNT
		MOV [SI],AL
		INC SI
		MOV [SI],'$'
		LEA DX,MSG3 
		MOV AH,09H
		INT 21H
		MOV AH,09H
		LEA DX,COUNT
		INT 21H
		JMP FINISH	 
	FAILURE:
		LEA DX,MSG4 
		MOV AH,09H
		INT 21H	
	FINISH:
		MOV AH,4CH
		INT 21H
END START
	
